spring.application.name=polleria

# Configuración de conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=PolleriaDB;encrypt=false;trustServerCertificate=true;instanceName=SQLEXPRESS
spring.datasource.username=polleriauser
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
